package mage.tournament.cubes;

import mage.game.draft.DraftCube;

/**
 * @author fireshoes
 */
public class AdamStyborskisPauperCube extends DraftCube {

    public AdamStyborskisPauperCube() {
        super("Adam Styborkski's Pauper Cube"); // https://docs.google.com/spreadsheets/d/12iQhC4bHqFW7hEWxPBjyC8yBDehFZ0_4DkqzyA8EL3o/edit#gid=0

        // last updated with CMR/KHM 7/22/2024
        cubeCards.add(new CardIdentity("Ancestral Blade", ""));
        cubeCards.add(new CardIdentity("Doomed Traveler", ""));
        cubeCards.add(new CardIdentity("Elite Vanguard", ""));
        cubeCards.add(new CardIdentity("Gideon's Lawkeeper", ""));
        cubeCards.add(new CardIdentity("Goldmeadow Harrier", ""));
        cubeCards.add(new CardIdentity("Hunted Witness", ""));
        cubeCards.add(new CardIdentity("Law-Rune Enforcer", ""));
        cubeCards.add(new CardIdentity("Savannah Lions", ""));
        cubeCards.add(new CardIdentity("Thraben Inspector", ""));
        cubeCards.add(new CardIdentity("Ardenvale Tactician", ""));
        cubeCards.add(new CardIdentity("Daring Skyjek", ""));
        cubeCards.add(new CardIdentity("Faerie Guidemother", ""));
        cubeCards.add(new CardIdentity("Kor Skyfisher", ""));
        cubeCards.add(new CardIdentity("Loyal Cathar", ""));
        cubeCards.add(new CardIdentity("Martyr of Dusk", ""));
        cubeCards.add(new CardIdentity("Mistral Charger", ""));
        cubeCards.add(new CardIdentity("Seeker of the Way", ""));
        cubeCards.add(new CardIdentity("Stormfront Pegasus", ""));
        cubeCards.add(new CardIdentity("Syndic of Tithes", ""));
        cubeCards.add(new CardIdentity("Whitemane Lion", ""));
        cubeCards.add(new CardIdentity("Attended Knight", ""));
        cubeCards.add(new CardIdentity("Aven Riftwatcher", ""));
        cubeCards.add(new CardIdentity("Heliod's Pilgrim", ""));
        cubeCards.add(new CardIdentity("Martyr's Soul", ""));
        cubeCards.add(new CardIdentity("Ordinary Pony", ""));
        cubeCards.add(new CardIdentity("Sandsteppe Outcast", ""));
        cubeCards.add(new CardIdentity("Warded Battlements", ""));
        cubeCards.add(new CardIdentity("Coalition Honor Guard", ""));
        cubeCards.add(new CardIdentity("Guardian of the Guildpact", ""));
        cubeCards.add(new CardIdentity("Rhox Veteran", ""));
        cubeCards.add(new CardIdentity("Seraph of Dawn", ""));
        cubeCards.add(new CardIdentity("Chivalrous Chevalier", ""));
        cubeCards.add(new CardIdentity("Custodi Squire", ""));
        cubeCards.add(new CardIdentity("Daybreak Chimera", ""));
        cubeCards.add(new CardIdentity("Supply-Line Cranes", ""));
        cubeCards.add(new CardIdentity("Totem-Guide Hartebeest", ""));
        cubeCards.add(new CardIdentity("Raise the Alarm", ""));
        cubeCards.add(new CardIdentity("Gather the Townsfolk", ""));
        cubeCards.add(new CardIdentity("Triplicate Spirits", ""));
        cubeCards.add(new CardIdentity("Battle Screech", ""));
        cubeCards.add(new CardIdentity("Call the Cavalry", ""));
        cubeCards.add(new CardIdentity("Gallant Cavalry", ""));
        cubeCards.add(new CardIdentity("Bonds of Faith", ""));
        cubeCards.add(new CardIdentity("Journey to Nowhere", ""));
        cubeCards.add(new CardIdentity("Pacifism", ""));
        cubeCards.add(new CardIdentity("Temporal Isolation", ""));
        cubeCards.add(new CardIdentity("Arrest", ""));
        cubeCards.add(new CardIdentity("Nahiri's Binding", ""));
        cubeCards.add(new CardIdentity("Oblivion Ring", ""));
        cubeCards.add(new CardIdentity("Faith's Fetters", ""));
        cubeCards.add(new CardIdentity("Ephemerate", ""));
        cubeCards.add(new CardIdentity("Gods Willing", ""));
        cubeCards.add(new CardIdentity("Dauntless Unity", ""));
        cubeCards.add(new CardIdentity("Otherworldly Journey", ""));
        cubeCards.add(new CardIdentity("Shelter", ""));
        cubeCards.add(new CardIdentity("Swift Response", ""));
        cubeCards.add(new CardIdentity("Borrowed Grace", ""));
        cubeCards.add(new CardIdentity("Prismatic Strands", ""));
        cubeCards.add(new CardIdentity("Blinding Beam", ""));
        cubeCards.add(new CardIdentity("Angelic Purge", ""));
        cubeCards.add(new CardIdentity("Settle Beyond Reality", ""));
        cubeCards.add(new CardIdentity("Witching Well", ""));
        cubeCards.add(new CardIdentity("Faerie Seer", ""));
        cubeCards.add(new CardIdentity("Carnivorous Death-Parrot", ""));
        cubeCards.add(new CardIdentity("Errant Ephemeron", ""));
        cubeCards.add(new CardIdentity("Erratic Visionary", ""));
        cubeCards.add(new CardIdentity("Eyekite", ""));
        cubeCards.add(new CardIdentity("Halimar Wavewatch", ""));
        cubeCards.add(new CardIdentity("Kitesail Corsair", ""));
        cubeCards.add(new CardIdentity("Ninja of the Deep Hours", ""));
        cubeCards.add(new CardIdentity("Omenspeaker", ""));
        cubeCards.add(new CardIdentity("Aether Adept", ""));
        cubeCards.add(new CardIdentity("Aven Eternal", ""));
        cubeCards.add(new CardIdentity("Cloudkin Seer", ""));
        cubeCards.add(new CardIdentity("Dimir Informant", ""));
        cubeCards.add(new CardIdentity("Dreamtail Heron", ""));
        cubeCards.add(new CardIdentity("Eldrazi Skyspawner", ""));
        cubeCards.add(new CardIdentity("Man-o'-War", ""));
        cubeCards.add(new CardIdentity("Mistral Singer", ""));
        cubeCards.add(new CardIdentity("Naiad of Hidden Coves", ""));
        cubeCards.add(new CardIdentity("Pestermite", ""));
        cubeCards.add(new CardIdentity("Shaper Parasite", ""));
        cubeCards.add(new CardIdentity("Skittering Crustacean", ""));
        cubeCards.add(new CardIdentity("Stitched Drake", ""));
        cubeCards.add(new CardIdentity("Warden of Evos Isle", ""));
        cubeCards.add(new CardIdentity("Wretched Gryff", ""));
        cubeCards.add(new CardIdentity("Cloaked Siren", ""));
        cubeCards.add(new CardIdentity("Mist Raven", ""));
        cubeCards.add(new CardIdentity("Shimmering Glasskite", ""));
        cubeCards.add(new CardIdentity("Thunder Drake", ""));
        cubeCards.add(new CardIdentity("Mnemonic Wall", ""));
        cubeCards.add(new CardIdentity("Mulldrifter", ""));
        cubeCards.add(new CardIdentity("Pondering Mage", ""));
        cubeCards.add(new CardIdentity("Watcher in the Mist", ""));
        cubeCards.add(new CardIdentity("Aethersnipe", ""));
        cubeCards.add(new CardIdentity("Striped Riverwinder", ""));
        cubeCards.add(new CardIdentity("Callous Dismissal", ""));
        cubeCards.add(new CardIdentity("Bubble Snare", ""));
        cubeCards.add(new CardIdentity("Omen of the Sea", ""));
        cubeCards.add(new CardIdentity("Claustrophobia", ""));
        cubeCards.add(new CardIdentity("Hieroglyphic Illumination", ""));
        cubeCards.add(new CardIdentity("Opt", ""));
        cubeCards.add(new CardIdentity("Repeal", ""));
        cubeCards.add(new CardIdentity("Counterspell", ""));
        cubeCards.add(new CardIdentity("Deliberate", ""));
        cubeCards.add(new CardIdentity("Deprive", ""));
        cubeCards.add(new CardIdentity("Mana Leak", ""));
        cubeCards.add(new CardIdentity("Miscalculation", ""));
        cubeCards.add(new CardIdentity("Remove Soul", ""));
        cubeCards.add(new CardIdentity("Snap", ""));
        cubeCards.add(new CardIdentity("Capsize", ""));
        cubeCards.add(new CardIdentity("Displace", ""));
        cubeCards.add(new CardIdentity("Rushing River", ""));
        cubeCards.add(new CardIdentity("Blink of an Eye", ""));
        cubeCards.add(new CardIdentity("Into the Roil", ""));
        cubeCards.add(new CardIdentity("Rain of Revelation", ""));
        cubeCards.add(new CardIdentity("Ray of Command", ""));
        cubeCards.add(new CardIdentity("Preordain", ""));
        cubeCards.add(new CardIdentity("Silent Departure", ""));
        cubeCards.add(new CardIdentity("Scour All Possibilities", ""));
        cubeCards.add(new CardIdentity("Treasure Cruise", ""));
        cubeCards.add(new CardIdentity("Deep Analysis", ""));
        cubeCards.add(new CardIdentity("Carrion Feeder", ""));
        cubeCards.add(new CardIdentity("Disowned Ancestor", ""));
        cubeCards.add(new CardIdentity("Plagued Rusalka", ""));
        cubeCards.add(new CardIdentity("Ruthless Ripper", ""));
        cubeCards.add(new CardIdentity("Typhoid Rats", ""));
        cubeCards.add(new CardIdentity("Boot Nipper", ""));
        cubeCards.add(new CardIdentity("Butcher Ghoul", ""));
        cubeCards.add(new CardIdentity("Doomed Dissenter", ""));
        cubeCards.add(new CardIdentity("Dusk Legion Zealot", ""));
        cubeCards.add(new CardIdentity("Gluttonous Slug", ""));
        cubeCards.add(new CardIdentity("Lazotep Reaver", ""));
        cubeCards.add(new CardIdentity("Putrid Goblin", ""));
        cubeCards.add(new CardIdentity("Sinuous Vermin", ""));
        cubeCards.add(new CardIdentity("Sultai Emissary", ""));
        cubeCards.add(new CardIdentity("Thrill-Kill Assassin", ""));
        cubeCards.add(new CardIdentity("Blade Juggler", ""));
        cubeCards.add(new CardIdentity("Bloodflow Connoisseur", ""));
        cubeCards.add(new CardIdentity("Crypt Rats", ""));
        cubeCards.add(new CardIdentity("Deathbloom Thallid", ""));
        cubeCards.add(new CardIdentity("Hired Blade", ""));
        cubeCards.add(new CardIdentity("Liliana's Specter", ""));
        cubeCards.add(new CardIdentity("Phyrexian Ghoul", ""));
        cubeCards.add(new CardIdentity("Phyrexian Rager", ""));
        cubeCards.add(new CardIdentity("Wakedancer", ""));
        cubeCards.add(new CardIdentity("Bone Picker", ""));
        cubeCards.add(new CardIdentity("Faceless Butcher", ""));
        cubeCards.add(new CardIdentity("Falkenrath Noble", ""));
        cubeCards.add(new CardIdentity("Gravedigger", ""));
        cubeCards.add(new CardIdentity("Gurmag Angler", ""));
        cubeCards.add(new CardIdentity("Thorn of the Black Rose", ""));
        cubeCards.add(new CardIdentity("Vulturous Aven", ""));
        cubeCards.add(new CardIdentity("Wicked Guardian", ""));
        cubeCards.add(new CardIdentity("Boneclad Necromancer", ""));
        cubeCards.add(new CardIdentity("Cavern Whisperer", ""));
        cubeCards.add(new CardIdentity("Predatory Nightstalker", ""));
        cubeCards.add(new CardIdentity("Silumgar Scavenger", ""));
        cubeCards.add(new CardIdentity("Warren Pilferers", ""));
        cubeCards.add(new CardIdentity("First-Sphere Gargantua", ""));
        cubeCards.add(new CardIdentity("Tithebearer Giant", ""));
        cubeCards.add(new CardIdentity("Fungal Infection", ""));
        cubeCards.add(new CardIdentity("Toll of the Invasion", ""));
        cubeCards.add(new CardIdentity("Moan of the Unhallowed", ""));
        cubeCards.add(new CardIdentity("Dead Weight", ""));
        cubeCards.add(new CardIdentity("Mire's Grasp", ""));
        cubeCards.add(new CardIdentity("Pestilence", ""));
        cubeCards.add(new CardIdentity("Defile", ""));
        cubeCards.add(new CardIdentity("Disfigure", ""));
        cubeCards.add(new CardIdentity("Tragic Slip", ""));
        cubeCards.add(new CardIdentity("Cast Down", ""));
        cubeCards.add(new CardIdentity("Last Gasp", ""));
        cubeCards.add(new CardIdentity("Nameless Inversion", ""));
        cubeCards.add(new CardIdentity("Vicious Offering", ""));
        cubeCards.add(new CardIdentity("Ob Nixilis's Cruelty", ""));
        cubeCards.add(new CardIdentity("Death Denied", ""));
        cubeCards.add(new CardIdentity("Unearth", ""));
        cubeCards.add(new CardIdentity("Feed The Swarm", ""));
        cubeCards.add(new CardIdentity("Morgue Theft", ""));
        cubeCards.add(new CardIdentity("Night's Whisper", ""));
        cubeCards.add(new CardIdentity("Ransack the Lab", ""));
        cubeCards.add(new CardIdentity("Read The Bones", ""));
        cubeCards.add(new CardIdentity("Evincar's Justice", ""));
        cubeCards.add(new CardIdentity("Fanatical Firebrand", ""));
        cubeCards.add(new CardIdentity("Frenzied Goblin", ""));
        cubeCards.add(new CardIdentity("Grim Initiate", ""));
        cubeCards.add(new CardIdentity("Insolent Neonate", ""));
        cubeCards.add(new CardIdentity("Jackal Pup", ""));
        cubeCards.add(new CardIdentity("Scorched Rusalka", ""));
        cubeCards.add(new CardIdentity("Burning Prophet", ""));
        cubeCards.add(new CardIdentity("Fireslinger", ""));
        cubeCards.add(new CardIdentity("Goblin Instigator", ""));
        cubeCards.add(new CardIdentity("Hobblefiend", ""));
        cubeCards.add(new CardIdentity("Keldon Marauders", ""));
        cubeCards.add(new CardIdentity("Mogg Flunkies", ""));
        cubeCards.add(new CardIdentity("Mogg War Marshal", ""));
        cubeCards.add(new CardIdentity("Orcish Hellraiser", ""));
        cubeCards.add(new CardIdentity("Rimrock Knight", ""));
        cubeCards.add(new CardIdentity("Viashino Pyromancer", ""));
        cubeCards.add(new CardIdentity("Bogardan Dragonheart", ""));
        cubeCards.add(new CardIdentity("Burning-Tree Vandal", ""));
        cubeCards.add(new CardIdentity("Ghirapur Gearcrafter", ""));
        cubeCards.add(new CardIdentity("Goblin Heelcutter", ""));
        cubeCards.add(new CardIdentity("Hissing Iguanar", ""));
        cubeCards.add(new CardIdentity("Inner-Flame Acolyte", ""));
        cubeCards.add(new CardIdentity("Irreverent Revelers", ""));
        cubeCards.add(new CardIdentity("Raging Kronch", ""));
        cubeCards.add(new CardIdentity("Storm Caller", ""));
        cubeCards.add(new CardIdentity("Tuktuk Rubblefort", ""));
        cubeCards.add(new CardIdentity("Viashino Sandsprinter", ""));
        cubeCards.add(new CardIdentity("Vulshok Sorcerer", ""));
        cubeCards.add(new CardIdentity("Beetleback Chief", ""));
        cubeCards.add(new CardIdentity("Keldon Raider", ""));
        cubeCards.add(new CardIdentity("Wildfire Elemental", ""));
        cubeCards.add(new CardIdentity("Quakefoot Cyclops", ""));
        cubeCards.add(new CardIdentity("Merchant of the Vale", ""));
        cubeCards.add(new CardIdentity("Dragon Fodder", ""));
        cubeCards.add(new CardIdentity("Forbidden Friendship", ""));
        cubeCards.add(new CardIdentity("Krenko's Command", ""));
        cubeCards.add(new CardIdentity("Hordeling Outburst", ""));
        cubeCards.add(new CardIdentity("Flurry of Horns", ""));
        cubeCards.add(new CardIdentity("Chandra's Magmutt", ""));
        cubeCards.add(new CardIdentity("Fissure Wizard", ""));
        cubeCards.add(new CardIdentity("Raid Bombardment", ""));
        cubeCards.add(new CardIdentity("Burst Lightning", ""));
        cubeCards.add(new CardIdentity("Lightning Bolt", ""));
        cubeCards.add(new CardIdentity("Pillar of Flame", ""));
        cubeCards.add(new CardIdentity("Abrade", ""));
        cubeCards.add(new CardIdentity("Fire Prophecy", ""));
        cubeCards.add(new CardIdentity("Heartfire", ""));
        cubeCards.add(new CardIdentity("Magma Jet", ""));
        cubeCards.add(new CardIdentity("Thrill of Possibility", ""));
        cubeCards.add(new CardIdentity("Dynacharge", ""));
        cubeCards.add(new CardIdentity("Staggershock", ""));
        cubeCards.add(new CardIdentity("Trumpet Blast", ""));
        cubeCards.add(new CardIdentity("Chain Lightning", ""));
        cubeCards.add(new CardIdentity("Firebolt", ""));
        cubeCards.add(new CardIdentity("Forked Bolt", ""));
        cubeCards.add(new CardIdentity("Reckless Charge", ""));
        cubeCards.add(new CardIdentity("Rift Bolt", ""));
        cubeCards.add(new CardIdentity("Skewer the Critics", ""));
        cubeCards.add(new CardIdentity("Arc Lightning", ""));
        cubeCards.add(new CardIdentity("Faithless Looting", ""));
        cubeCards.add(new CardIdentity("Pyrotechnics", ""));
        cubeCards.add(new CardIdentity("Elvish Mystic", ""));
        cubeCards.add(new CardIdentity("Llanowar Elves", ""));
        cubeCards.add(new CardIdentity("Squirrel Dealer", ""));
        cubeCards.add(new CardIdentity("Young Wolf", ""));
        cubeCards.add(new CardIdentity("Ambush Viper", ""));
        cubeCards.add(new CardIdentity("Brindle Shoat", ""));
        cubeCards.add(new CardIdentity("Mother Bear", ""));
        cubeCards.add(new CardIdentity("Sakura-Tribe Elder", ""));
        cubeCards.add(new CardIdentity("Thornweald Archer", ""));
        cubeCards.add(new CardIdentity("Wall of Roots", ""));
        cubeCards.add(new CardIdentity("Werebear", ""));
        cubeCards.add(new CardIdentity("Wild Mongrel", ""));
        cubeCards.add(new CardIdentity("Hooting Mandrills", ""));
        cubeCards.add(new CardIdentity("Jungleborn Pioneer", ""));
        cubeCards.add(new CardIdentity("Rubbleback Rhino", ""));
        cubeCards.add(new CardIdentity("Scion Summoner", ""));
        cubeCards.add(new CardIdentity("Yavimaya Elder", ""));
        cubeCards.add(new CardIdentity("Yavimaya Sapherd", ""));
        cubeCards.add(new CardIdentity("Aerie Bowmasters", ""));
        cubeCards.add(new CardIdentity("Fierce Witchstalker", ""));
        cubeCards.add(new CardIdentity("Jade Guardian", ""));
        cubeCards.add(new CardIdentity("Penumbra Spider", ""));
        cubeCards.add(new CardIdentity("Primal Huntbeast", ""));
        cubeCards.add(new CardIdentity("Voracious Typhon", ""));
        cubeCards.add(new CardIdentity("Aerie Ouphes", ""));
        cubeCards.add(new CardIdentity("Conclave Naturalists", ""));
        cubeCards.add(new CardIdentity("Lifecraft Cavalry", ""));
        cubeCards.add(new CardIdentity("Nessian Asp", ""));
        cubeCards.add(new CardIdentity("Silverback Shaman", ""));
        cubeCards.add(new CardIdentity("Rampaging Hippo", ""));
        cubeCards.add(new CardIdentity("Wrecking Beast", ""));
        cubeCards.add(new CardIdentity("Elephant Ambush", ""));
        cubeCards.add(new CardIdentity("Saproling Migration", ""));
        cubeCards.add(new CardIdentity("Llanowar Visionary", ""));
        cubeCards.add(new CardIdentity("Trumpeting Herd", ""));
        cubeCards.add(new CardIdentity("Scatter the Seeds", ""));
        cubeCards.add(new CardIdentity("Krosan Tusker", ""));
        cubeCards.add(new CardIdentity("Rancor", ""));
        cubeCards.add(new CardIdentity("Cartouche of Strength", ""));
        cubeCards.add(new CardIdentity("Elephant Guide", ""));
        cubeCards.add(new CardIdentity("Moldervine Cloak", ""));
        cubeCards.add(new CardIdentity("Giant Growth", ""));
        cubeCards.add(new CardIdentity("Ranger's Guile", ""));
        cubeCards.add(new CardIdentity("Grapple with the Past", ""));
        cubeCards.add(new CardIdentity("Ram Through", ""));
        cubeCards.add(new CardIdentity("Titanic Brawl", ""));
        cubeCards.add(new CardIdentity("Vines of Vastwood", ""));
        cubeCards.add(new CardIdentity("Band Together", ""));
        cubeCards.add(new CardIdentity("Clear Shot", ""));
        cubeCards.add(new CardIdentity("Pulse of Murasa", ""));
        cubeCards.add(new CardIdentity("Wildsize", ""));
        cubeCards.add(new CardIdentity("Prey Upon", ""));
        cubeCards.add(new CardIdentity("Savage Swipe", ""));
        cubeCards.add(new CardIdentity("Adventure Awaits", ""));
        cubeCards.add(new CardIdentity("Epic Confrontation", ""));
        cubeCards.add(new CardIdentity("Nature's Lore", ""));
        cubeCards.add(new CardIdentity("Rampant Growth", ""));
        cubeCards.add(new CardIdentity("Selfie Preservation", ""));
        cubeCards.add(new CardIdentity("Track Down", ""));
        cubeCards.add(new CardIdentity("Winding Way", ""));
        cubeCards.add(new CardIdentity("Nissa's Pilgrimage", ""));
        cubeCards.add(new CardIdentity("Deputy of Acquittals", ""));
        cubeCards.add(new CardIdentity("Curse of Chains", ""));
        cubeCards.add(new CardIdentity("Lawmage's Binding", ""));
        cubeCards.add(new CardIdentity("Feeling of Dread", ""));
        cubeCards.add(new CardIdentity("Momentary Blink", ""));
        cubeCards.add(new CardIdentity("Cavern Harpy", ""));
        cubeCards.add(new CardIdentity("Dimir Guildmage", ""));
        cubeCards.add(new CardIdentity("Dinrova Horror", ""));
        cubeCards.add(new CardIdentity("Agony Warp", ""));
        cubeCards.add(new CardIdentity("Soul Manipulation", ""));
        cubeCards.add(new CardIdentity("Spike Jester", ""));
        cubeCards.add(new CardIdentity("Kathari Bomber", ""));
        cubeCards.add(new CardIdentity("Terminate", ""));
        cubeCards.add(new CardIdentity("Blightning", ""));
        cubeCards.add(new CardIdentity("Auger Spree", ""));
        cubeCards.add(new CardIdentity("Burning-Tree Emissary", ""));
        cubeCards.add(new CardIdentity("Frenzied Arynx", ""));
        cubeCards.add(new CardIdentity("Colossal Might", ""));
        cubeCards.add(new CardIdentity("Branching Bolt", ""));
        cubeCards.add(new CardIdentity("Savage Smash", ""));
        cubeCards.add(new CardIdentity("Qasali Pridemage", ""));
        cubeCards.add(new CardIdentity("Rosemane Centaur", ""));
        cubeCards.add(new CardIdentity("Safehold Elite", ""));
        cubeCards.add(new CardIdentity("Call of the Conclave", ""));
        cubeCards.add(new CardIdentity("Sigil Blessing", ""));
        cubeCards.add(new CardIdentity("Imperious Oligarch", ""));
        cubeCards.add(new CardIdentity("Kingpin's Pet", ""));
        cubeCards.add(new CardIdentity("Pillory of the Sleepless", ""));
        cubeCards.add(new CardIdentity("Final Payment", ""));
        cubeCards.add(new CardIdentity("Unmake", ""));
        cubeCards.add(new CardIdentity("Putrid Leech", ""));
        cubeCards.add(new CardIdentity("Desecrator Hag", ""));
        cubeCards.add(new CardIdentity("Golgari Rotwurm", ""));
        cubeCards.add(new CardIdentity("Grisly Salvage", ""));
        cubeCards.add(new CardIdentity("Consume Strength", ""));
        cubeCards.add(new CardIdentity("Winged Coatl", ""));
        cubeCards.add(new CardIdentity("Coiling Oracle", ""));
        cubeCards.add(new CardIdentity("Shambleshark", ""));
        cubeCards.add(new CardIdentity("Aeromunculus", ""));
        cubeCards.add(new CardIdentity("Snakeform", ""));
        cubeCards.add(new CardIdentity("Goblin Electromancer", ""));
        cubeCards.add(new CardIdentity("Izzet Chronarch", ""));
        cubeCards.add(new CardIdentity("Fire // Ice", ""));
        cubeCards.add(new CardIdentity("Jilt", ""));
        cubeCards.add(new CardIdentity("Hypothesizzle", ""));
        cubeCards.add(new CardIdentity("Wojek Halberdiers", ""));
        cubeCards.add(new CardIdentity("Skyknight Legionnaire", ""));
        cubeCards.add(new CardIdentity("Viashino Firstblade", ""));
        cubeCards.add(new CardIdentity("Rally the Peasants", ""));
        cubeCards.add(new CardIdentity("War Flare", ""));
        cubeCards.add(new CardIdentity("Flayer Husk", ""));
        cubeCards.add(new CardIdentity("Renegade Freighter", ""));
        cubeCards.add(new CardIdentity("Sickleslicer", ""));
        cubeCards.add(new CardIdentity("Gingerbrute", ""));
        cubeCards.add(new CardIdentity("Sparring Construct", ""));
        cubeCards.add(new CardIdentity("Vault Skirge", ""));
        cubeCards.add(new CardIdentity("Perilous Myr", ""));
        cubeCards.add(new CardIdentity("Porcelain Legionnaire", ""));
        cubeCards.add(new CardIdentity("Cogwork Librarian", ""));
        cubeCards.add(new CardIdentity("Peace Strider", ""));
        cubeCards.add(new CardIdentity("Pierce Strider", ""));
        cubeCards.add(new CardIdentity("Prophet of The Peak", ""));
        cubeCards.add(new CardIdentity("Gathan Raiders", ""));
        cubeCards.add(new CardIdentity("Kozilek's Channeler", ""));
        cubeCards.add(new CardIdentity("Eldrazi Devastator", ""));
        cubeCards.add(new CardIdentity("Ulamog's Crusher", ""));
        cubeCards.add(new CardIdentity("Adventuring Gear", ""));
        cubeCards.add(new CardIdentity("Bonesplitter", ""));
        cubeCards.add(new CardIdentity("Leonin Bola", ""));
        cubeCards.add(new CardIdentity("Sylvok Lifestaff", ""));
        cubeCards.add(new CardIdentity("Wayfarer's Bauble", ""));
        cubeCards.add(new CardIdentity("Guardian Idol", ""));
        cubeCards.add(new CardIdentity("Mind Stone", ""));
        cubeCards.add(new CardIdentity("Prophetic Prism", ""));
        cubeCards.add(new CardIdentity("Star Compass", ""));
        cubeCards.add(new CardIdentity("Vulshok Morningstar", ""));
        cubeCards.add(new CardIdentity("Pristine Talisman", ""));
        cubeCards.add(new CardIdentity("Serrated Arrows", ""));
        cubeCards.add(new CardIdentity("Skyscanner", ""));
        cubeCards.add(new CardIdentity("Thriving Heath", ""));
        cubeCards.add(new CardIdentity("Thriving Isle", ""));
        cubeCards.add(new CardIdentity("Thriving Moor", ""));
        cubeCards.add(new CardIdentity("Thriving Bluff", ""));
        cubeCards.add(new CardIdentity("Thriving Grove", ""));
        cubeCards.add(new CardIdentity("Azorius Guildgate", ""));
        cubeCards.add(new CardIdentity("Secluded Steppe", ""));
        cubeCards.add(new CardIdentity("Tranquil Cove", ""));
        cubeCards.add(new CardIdentity("Barren Moor", ""));
        cubeCards.add(new CardIdentity("Dimir Guildgate", ""));
        cubeCards.add(new CardIdentity("Dismal Backwater", ""));
        cubeCards.add(new CardIdentity("Bloodfell Caves", ""));
        cubeCards.add(new CardIdentity("Rakdos Guildgate", ""));
        cubeCards.add(new CardIdentity("Tranquil Thicket", ""));
        cubeCards.add(new CardIdentity("Gruul Guildgate", ""));
        cubeCards.add(new CardIdentity("Lonely Sandbar", ""));
        cubeCards.add(new CardIdentity("Rugged Highlands", ""));
        cubeCards.add(new CardIdentity("Blossoming Sands", ""));
        cubeCards.add(new CardIdentity("Forgotten Cave", ""));
        cubeCards.add(new CardIdentity("Selesnya Guildgate", ""));
        cubeCards.add(new CardIdentity("Orzhov Guildgate", ""));
        cubeCards.add(new CardIdentity("Scoured Barrens", ""));
        cubeCards.add(new CardIdentity("Golgari Guildgate", ""));
        cubeCards.add(new CardIdentity("Jungle Hollow", ""));
        cubeCards.add(new CardIdentity("Simic Guildgate", ""));
        cubeCards.add(new CardIdentity("Thornwood Falls", ""));
        cubeCards.add(new CardIdentity("Izzet Guildgate", ""));
        cubeCards.add(new CardIdentity("Swiftwater Cliffs", ""));
        cubeCards.add(new CardIdentity("Boros Guildgate", ""));
        cubeCards.add(new CardIdentity("Wind-Scarred Crag", ""));
        cubeCards.add(new CardIdentity("Ash Barrens", ""));
        cubeCards.add(new CardIdentity("Evolving Wilds", ""));
        cubeCards.add(new CardIdentity("Terramorphic Expanse", ""));
        cubeCards.add(new CardIdentity("Warped Landscape", ""));
        cubeCards.add(new CardIdentity("Desert", ""));
    }
}
